# Generated by Django 4.1.4 on 2023-01-15 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_content_post_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
